### ISSUE TITLE
呃，这个...看起来性能很屌啊

### ISSUE THREAD

**Issue by yyxx9988** [aizuyan/pinyin#1]
支持一个，哈哈

**Comment by yyxx9988** [comment]
啧啧，你这个性能测试结果... 求 @overtrue 大神心里阴影面积... 哈哈~

**Comment by overtrue** [comment]
@duruitang 不明白呢？为何要有心里阴影呢？

**Comment by yyxx9988** [comment]
@overtrue 哈哈，开玩笑而已~

**Comment by overtrue** [comment]
@duruitang PHP 与 C 比性能根本就不是一个级别嘛。

**Comment by yyxx9988** [comment]
@overtrue 不过一般情况下我还是会继续用非php扩展版的，原因一：overtrue/pinyin 用composer随时可以更新升级；原因二：扩展版这玩意常驻内存，小内存服务器还是节省点好。特殊情况下，用扩展包更高效。总之，二位大神，小弟拜服你们了，哈哈~

**Comment by overtrue** [comment]
@duruitang 嗯，对的，各有利弊，不同的使用场景，不同水平的开发者，使用不同的方案。这样才会完美嘛。:laughing:

**Comment by yyxx9988** [comment]
@overtrue :+1:

**Comment by aizuyan** [comment]
@overtrue 我只想说一点，我看到你这个汉字转拼音的实现的时候，惊呆了，你太聪明了，膜拜前辈

**Comment by overtrue** [comment]
@aizuyan 也是更新了两版才出来的，之前第一版的时候是整体加载到内存，后来有人抱怨占用太大（8M左右），然后我就弄成了现在的版本（分片，时间换空间）。互相学习！
